name: flux_cli
description: A Very Good Project created by Very Good CLI.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.3.0
  equatable: ^2.0.5
  mason_logger: ^0.2.4
  pub_updater: ^0.3.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  dart_code_metrics: ^5.7.5
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1

executables:
  flux:
